name: Build Plugin

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build with Maven
      run: mvn package

    - name: Upload Plugin Jar
      uses: actions/upload-artifact@v4
      with:
        name: PhanToMTunnelPlugin
        path: target/*.jar
